config/routes.rb
Rails.application.routes.draw do

  root 'bills#index'

  resources :bills

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  def index
    @bills = Bill.all
    @unpaid_bills = @bills.sort
  end

  def show
  end

  def new
    @bill = Bill.new
  end

  def create
    @bill = Bill.new(bill_params)
    if @bill.save
      redirect_to bill_path(@bill.id), notice: 'Bill has been added'
    else
      render :new, alert: 'Error creating bill'
    end
  end

  def edit
  end

  def update
    if @bill.update_attributes(bill_params)
      redirect_to bill_path(@bill.id), notice: 'Bill has been updated'
    else
      render :edit, alert: 'Error updating bill'
    end
  end

  def destroy
    @bill.destroy
    redirect_to bills_path, alert: 'Bill has been deleted'
  end

  private

  # def find_unpaid_bills
  #   @unpaid_bills = @bills.each { |bill| bill.paid == false }
  # end

  def set_bill
    @bill = Bill.find(params[:id])
  end

  def bill_params
    params.require(:bill).permit(:title, :amount, :due_at, :paid)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_notice_message
    unless flash.empty?
      [:notice, :alert].each do |key|
        return content_tag(:div, flash[key], class: "flash-#{key}") if flash[key].present?
      end
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<div class="row">
  <div class="col-sm-12 text-center">
    <%= form_for(@bill) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :amount %>
      <%= f.text_field :amount %>

      <%= f.label :due_at %>
      <%= f.text_field :due_at %>

      <%= f.label :paid %>
      <%= f.check_box :paid %>

      <%= f.submit %>
    <% end %>

  </div>
</div>

app/views/bills/edit.html.erb
<div class="text-center">
  <h1>Edit <%= @bill.title %></h1>
</div>
<%= render 'form' %>

app/views/bills/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h1>My Bizzizles</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 text-center">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h2 class="panel-title">Current Bills</h2>
        </div>
        <div class="panel-body">
          <% @bills.each do |bill| %>
            <h4><%= link_to bill.title, bill_path(bill.id) if bill.paid %></h4>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-6 text-center">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">Passed Due</h2>
        </div>
        <div class="panel-body">
          <% @unpaid_bills.each do |bill| %>
            <h4><%= link_to bill.title, bill_path(bill.id) if bill.paid == false %></h4>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row text-center">
    <button class="btn btn-default">
      <%= link_to 'Add Bill', new_bill_path %>
    </button>
  </div>
</div>

app/views/bills/new.html.erb
<div class="text-center">
  <h1>Add Bill</h1>
</div>
<%= render 'form' %>

app/views/bills/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h1><%= @bill.title.upcase %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 text-center">
      <p>Amount: <%= @bill.amount.nil? ? "Need amount" : "$#{@bill.amount}" %></p>
      <p>Due At: <%= @bill.due_at %></p>
      <h4>Paid: <%= @bill.paid %></h4>
    </div>
  </div>
  <div class="row text-center">
    <button class="btn btn-info">
      <%= link_to 'Edit Bill', edit_bill_path %>
    </button>
    <button class="btn btn-danger">
      <%= link_to 'Delete Bill', bill_path, method: :delete %>
    </button>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to 'My Bills', bills_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillTracker</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/nav' %>
      <%= show_notice_message %>
      <%= yield %>
      <%= javascript_include_tag 'application' %>
    </div>
  </body>
</html>